name: mybill_web
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.0
  video_player: ^2.8.2
  flutter_html: ^2.2.1
  uuid: ^4.3.3
  carousel_slider: ^4.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/List.png
    - assets/main.png
    - assets/X.png
    - assets/TextFaq.png
    - assets/downArrow.png
    - assets/mybillLogo.png
    - assets/Logo.png
    - assets/icons/
    - assets/

  fonts:
    - family: AppleSDGothicNeo
      fonts:
        - asset: assets/fonts/AppleSDGothicNeoR.ttf # REGULAR
          weight: 400
        - asset: assets/fonts/AppleSDGothicNeoR.ttf # REGULAR
          weight: 500
        - asset: assets/fonts/AppleSDGothicNeoSB.ttf # SEMI BOLD
          weight: 600
        - asset: assets/fonts/AppleSDGothicNeoB.ttf # BOLD
          weight: 700
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf